fix compilation error -Werror=pessimizing-move
since compiler updated current code resulted in the following
error:

error: moving a local object in a return statement prevents copy
elision [-Werror=pessimizing-move]

issue: LBM1-13338